// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "defaultTheme": string;
      "customVariablesJSON": string;
      "clickBehavior": string;
      "showToolbar": boolean;
    };
  }
}
